; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM12
monitor_port = COM12
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
build_flags = 
	-D ASYNCWEBSERVER_REGEX 
	-D BOARD_HAS_PSRAM
	-D ARDUINO_ESP32S3_DEV
	-mfix-esp32-psram-cache-issue
	-D CONFIG_MBEDTLS_CERTIFICATE_BUNDLE=1
	-D CONFIG_MBEDTLS_CERTIFICATE_BUNDLE_DEFAULT_FULL=1
	-D CONFIG_SPIRAM_USE_MALLOC=1
	-D CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC=1
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	arduino-libraries/Ethernet
	arduino-libraries/NTPClient@^3.2.1
	etlcpp/Embedded Template Library@^20.47.1
	bblanchon/ArduinoJson@^7.2.2
	ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
