; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
board_build.partitions = min_spiffs.csv
build_flags = -D ASYNCWEBSERVER_REGEX
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
	arduino-libraries/Ethernet
	arduino-libraries/NTPClient@^3.2.1
	etlcpp/Embedded Template Library@^20.47.1
	bblanchon/ArduinoJson@^7.2.2
	ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
